# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
# on:
# Schedule the action to run every day
#   schedule: [{cron: "0 0"}]
#   Lines below let you run workflow manually and on each commit
#   workflow_dispatch:
on:
  schedule:
    - cron:  '59 23 1,6,11,16,21,26 * *'
  workflow_dispatch:
  push: {branches: ["master", "main"]}
  pull_request:
    branches: 'master'
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          user: umairjibran
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Karachi
          plugin_introduction: yes
#           plugin_lines: yes
#           plugin_achievements: yes
#           plugin_achievements_only: >-
#             polyglot, stargazer, sponsor, deployer, member, maintainer, developer,
#             scripter, packager, explorer, infographile, manager
#           plugin_achievements_display: compact
#           plugin_habits: yes
#           plugin_habits_facts: yes
#           plugin_habits_charts: no
#           plugin_achievements_limit: 10
#           plugin_achievements_secrets: yes
#           plugin_achievements_threshold: C
#           plugin_habits_charts_type: classic
#           plugin_habits_days: 14
#           plugin_habits_from: 200
#           plugin_habits_languages_limit: 8
#           plugin_habits_languages_threshold: repositories_batch
#           plugin_languages: yes
#           plugin_languages_aliases: javascript:JS typescript:TS
#           plugin_languages_analysis_timeout: 15
#           plugin_languages_categories: markup, programming
#           plugin_languages_colors: github
#           plugin_languages_ignored: css
#           plugin_languages_limit: 8
#           plugin_languages_recent_categories: markup, programming
#           plugin_languages_recent_days: 14
#           plugin_languages_recent_load: 300
#           plugin_languages_sections: most-used
#           plugin_languages_threshold: 0%
