# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
# on:
# Schedule the action to run every day
#   schedule: [{cron: "0 0"}]
#   Lines below let you run workflow manually and on each commit
#   workflow_dispatch:
on:
  schedule:
    - cron:  '59 23 1,6,11,16,21,26 * *'
  workflow_dispatch:
  push: {branches: ["master", "main"]}
  pull_request:
    branches: '*'
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          user: umairjibran
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Karachi
          plugin_introduction: yes
          plugin_lines: yes
          plugin_achievements: yes
          plugin_achievements_only: >-
            polyglot, stargazer, sponsor, deployer, member, maintainer, developer,
            scripter, packager, explorer, infographile, manager
          plugin_achievements_display: compact
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
